### ISSUE TITLE
Internal Server Error, json doesn't get written to.

### ISSUE THREAD

**Issue by NylaTheWolf** [karlicoss/pockexport#14]
I wanted to try out this script but I ended up with an internal server error after a few runs, but the pages that did get processed were not written to the file.

```
python -m pockexport.export --secrets /Users/nyla/Documents/secrets.py >"/Users/nyla/Documents/Pocket-Export$(date -I).json"
/Users/nyla/pers_venv/lib/python3.10/site-packages/pockexport/exporthelpers/logging_helper.py:136: UserWarning: You might want to 'pip install colorlog' for nice colored logs
  warnings.warn("You might want to 'pip install colorlog' for nice colored logs")
[DEBUG   2024-10-11 00:54:57,253 __main__ export.py:37  ] retrieving from offset=0 (expected total=None)
[DEBUG   2024-10-11 00:54:57,962 __main__ export.py:37  ] retrieving from offset=30 (expected total=5000)
[DEBUG   2024-10-11 00:54:58,597 __main__ export.py:37  ] retrieving from offset=60 (expected total=5000)
[DEBUG   2024-10-11 00:54:59,169 __main__ export.py:37  ] retrieving from offset=90 (expected total=5000)
[DEBUG   2024-10-11 00:54:59,727 __main__ export.py:37  ] retrieving from offset=120 (expected total=5000)
[DEBUG   2024-10-11 00:55:00,390 __main__ export.py:37  ] retrieving from offset=150 (expected total=5000)
[DEBUG   2024-10-11 00:55:01,169 __main__ export.py:37  ] retrieving from offset=180 (expected total=5000)
[DEBUG   2024-10-11 00:55:01,832 __main__ export.py:37  ] retrieving from offset=210 (expected total=5000)
[DEBUG   2024-10-11 00:55:02,492 __main__ export.py:37  ] retrieving from offset=240 (expected total=5000)
[DEBUG   2024-10-11 00:55:03,576 __main__ export.py:37  ] retrieving from offset=270 (expected total=5000)
[DEBUG   2024-10-11 00:55:14,412 __main__ export.py:37  ] retrieving from offset=300 (expected total=5000)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/nyla/pers_venv/lib/python3.10/site-packages/pockexport/export.py", line 104, in <module>
    main()
  File "/Users/nyla/pers_venv/lib/python3.10/site-packages/pockexport/export.py", line 84, in main
    j = get_json(**params)
  File "/Users/nyla/pers_venv/lib/python3.10/site-packages/pockexport/export.py", line 74, in get_json
    return Exporter(**params).export_json()
  File "/Users/nyla/pers_venv/lib/python3.10/site-packages/pockexport/export.py", line 60, in export_json
    assert res.get('error') is None, res  # just in case
AssertionError: {'error': 'Internal server error'}
```

Do you know what went wrong?

**Comment by karlicoss** [comment]
Hey -- I got same error a couple of times in the past week (I have daily exports) -- it's possible they are experiencing some intermittent issues? 
I'll see if it keeps happening (let me know as well if you retry and it works or doesn't!). If it still happening, I will modify the code to be a bit more defensive, e.g. retry individual requests in case of server error

**Comment by NylaTheWolf** [comment]
It was able to reach offset=390 this time but I got the error again.

Is there a way I can pass in parameters to get a limit of the items I want to receive so I don't overload the servers with the amount of items I have and I can get some of my saved items written immediately?

**Comment by karlicoss** [comment]
Hey, I pushed a fix to master that should retry in case of internal server error -- you wanna try it out? 

There are a couple of problems with the limit on number of items

- most of the export is actually useless "deleted" items -- sadly there is no way to filter them out, so we end up having to query the api for everything. And the actually useful items are spread out over the whole api export
- error could occur on any request, so there won't be a sustainable way to run this script regularly. Unless you just want a one-off export? But in that case you could as well just use manual export or GDPR export or something like that? :)
